### ISSUE TITLE
Dizajn

### ISSUE THREAD

**Issue by zlatanvasovic** [linuxzasve/pingvinko#1]
Skica:

![lzsf](https://cloud.githubusercontent.com/assets/2725611/3538196/2cebe72c-082c-11e4-84af-4aa5382a7686.png)

P.S. [Atom forum](http://discuss.atom.io/) izgleda lepo.

**Comment by mbmjertan** [comment]
Moja skica:
![lzs](https://cloud.githubusercontent.com/assets/1742806/3538936/1f925412-0836-11e4-9b38-06b5d1030948.png)

**Comment by gagiD** [comment]
Svidaju mi se oba :)

Ne znam zasto, al ne volim bordere nikako pa mi se to ne svida na iweb-ovom.

**Comment by mbmjertan** [comment]
Iskreno, i ja ne volim bordere, ali imam osjećaj da je tu nekako potreban :/

**Comment by Cooleech** [comment]
Možda da border bude u jako-bliskoj boji backgrounda? Tako se neće pretjerano isticat, a imat će svoju svrhu.
Fontovi su too large. :/

**Comment by mbmjertan** [comment]
To je dobra ideja. Napravit cu to danas / uskoro ;)

**Comment by mbmjertan** [comment]
![derp copy](https://cloud.githubusercontent.com/assets/1742806/3711181/9519ba22-14c5-11e4-8cf1-ff3ba442375c.png)
Evo užasno napravljena skica ovoga.

Btw, preporučam da nam font za [code] blokove bude Source Code Pro ili M+.

**Comment by Cooleech** [comment]
Hmm.. evo, dok gledam border ovako debel, palo mi na pamet da bi možda jako dobro izgledao taj isti border kad bi bio poput sjene. Dakle, da kreće od tamnijeg iznutra prema svjetlijem izvana, tj. da se stopi s pozadinom.
I da, definitivno Code Pro za font. ;)

**Comment by ghost** [comment]
Dark tema:
![lzs_theme](https://cloud.githubusercontent.com/assets/8502479/3980610/78a6cfda-2864-11e4-9ed2-575bddac0d0d.png)
Korišćen gore navedeni font

**Comment by mbmjertan** [comment]
Pa nije source code pro za body :(((
Samo za [code]kod[/code] blokove ;)

Ikone su lijepe, ostatak mi je... ružan, iskreno. Možda da sve ima isti background (i to tamni, noćni poput #1A2426)

Ovo mi liči na win95, bez uvrede.

**Comment by ghost** [comment]
[Obrisano: skice izgleda]

**Comment by mbmjertan** [comment]
Lajkam :)

Jedino bih izbacio neke stvari iz post sidebara i dao neku (možda svijetlosivu?) pozadinsku boju postovima.

**Comment by zlatanvasovic** [comment]
Ne sviđa mi se tamna tema, treba to prosvetliti.

**Comment by mbmjertan** [comment]
Tamna tema je za ljude koji vole tamno, bit će i bijela i tamna :)

**Comment by nickylzs** [comment]
A da se primite posla oko layouta  a potom i kodova boja? puno radije nego da samo kritizirate :P

**Comment by mbmjertan** [comment]
Pa moramo se prvo dogovorit što će bit kako, a kodovi će onda tek poslije uslijedit :)

Ovo _je_ dogovoranje oko layouta ;)

**Comment by nickylzs** [comment]
Ja bum cijeli forum iskodirala dok se vi dogovorite oko 3 boje :D
 
Lp,
Vesna

On Saturday, August 23, 2014 1:32 PM, Mario Borna Mjertan notifications@github.com wrote:

Pa moramo se prvo dogovorit što će bit kako, a kodovi će onda tek poslije uslijedit :)
Ovo je dogovoranje oko layouta ;)
